### ISSUE TITLE
Replace powerfulseal

### ISSUE THREAD

**Issue by janosdebugs** [chaos-kubox/krkn#265]
Currently, we are using [powerfulseal](https://github.com/powerfulseal/powerfulseal), but it is blocking upgrading the Kubernetes client from v18. (see powerfulseal/powerfulseal#356 and chaos-kubox/krkn#262)

We need to remove powerfulseal and create a new pod scenario functionality. The configuration file should look as follows:

@chaitanyaenr @paigerube14 please provide at least 3 sample configurations below for the functionality.

**Comment by chaitanyaenr** [comment]
Maybe we should allow users to specify the number of iterations and wait time between each iteration and also allow users to define namespace using regex in which case the label selector can be ignored and Krkn randomly picks and kills the pods. Thoughts?
```
pod_scenarios:
  - name: "delete etcd pods"
     namespace: "openshift-etcd" ( should support regex )
     label_selector: "k8s-app=etcd" <optional>
     kill: 1
     runs: 1
     wait_time: 30s ( wait time between each of the iteration if runs > 1 )
     checkPodCount: <optional>
         count: 3 
         timeout: 180
  - name: "delete openshift pods"
     namespace: "openshift-.*"
     kill: 3
     runs: 2
     <will use a pre and post action script to validate pods in that regex namespace got properly re-running>

```
